<?php

namespace PortfolioBundle\Repository;

use PortfolioBundle\Entity\education;

/**
 * educationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class educationRepository extends \Doctrine\ORM\EntityRepository
{
    public function exist($var1,$var2)
    {
        $query=$this->getEntityManager()->createQuery("select c FROM PortfolioBundle:education c");
        if($var1=c.typeofeducaion && $var2=c.descrption){
            return 1;
        }

        return $query->getResult();
    }
}
