<?php

namespace PortfolioBundle\Repository;

/**
 * interestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class interestsRepository extends \Doctrine\ORM\EntityRepository
{
}
