<?php

namespace PortfolioBundle\Repository;

/**
 * skillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class skillsRepository extends \Doctrine\ORM\EntityRepository
{
}
