<?php

namespace PortfolioBundle\Repository;

/**
 * workexperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workexperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
